--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CJMustard1452/PocketTranslate
build-by-default: true
branches:
- main
projects:
  PocketTranslate:
    path: ""
    icon: "icon.png"
...
