---
name: PocketTranslate
version: 1.1.0
main: CJMustard1452\translate\Loader
api: 5.15.0
src-namespace-prefix: CJMustard1452\translate

permissions:
  pockettranslate.setlanguage.cmd:
    default: true
...
